name: CI Tests
on:
  push:
    branches:
      - main

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Set up Python 3.11
              uses: actions/setup-python@v2
              with:
                python-version: 3.11.3
            
            - name: Install dependencies
              working-directory: "./"
              run: pip install pipenv && pipenv install --dev
            
            - name: Lint
              working-directory: "./"
              run: pipenv run pylint --recursive=y .